"""
DataForge AI - Deterministic data profiling.
Every number here is computed directly by pandas/numpy. Nothing is
guessed or generated by an AI model.
"""
import math
import numpy as np
import pandas as pd

DATE_HINT_WORDS = ("date", "time", "day", "month", "year", "created", "updated", "timestamp")


def _clean_scalar(v):
    """Make a value JSON-serialisable (handles numpy/pandas NaN, Timestamp, numpy scalar types)."""
    if v is None:
        return None
    if isinstance(v, (np.generic,)):
        v = v.item()
    if isinstance(v, float) and (math.isnan(v) or math.isinf(v)):
        return None
    if isinstance(v, pd.Timestamp):
        return v.isoformat()
    return v


def detect_column_types(df: pd.DataFrame) -> dict:
    """Classify each column as numeric / date / text. Deterministic heuristics only."""
    types = {}
    for col in df.columns:
        series = df[col]
        if pd.api.types.is_numeric_dtype(series):
            types[col] = "numeric"
            continue
        if pd.api.types.is_datetime64_any_dtype(series):
            types[col] = "date"
            continue
        # Try to detect date-like text columns: name hints + high parse success rate
        name_hint = any(w in str(col).lower() for w in DATE_HINT_WORDS)
        sample = series.dropna().astype(str)
        if len(sample) > 0:
            sample_test = sample.head(min(50, len(sample)))
            try:
                parsed = pd.to_datetime(sample_test, errors="coerce", format="mixed")
            except (ValueError, TypeError):
                parsed = pd.to_datetime(sample_test, errors="coerce")
            success_rate = parsed.notna().mean() if len(sample_test) else 0
            if success_rate >= 0.85 and (name_hint or success_rate >= 0.95):
                types[col] = "date"
                continue
        types[col] = "text"
    return types


def build_profile(df: pd.DataFrame) -> dict:
    """Build a complete, professional dataset profile. All values are calculated, not invented."""
    n_rows = int(df.shape[0])
    n_cols = int(df.shape[1])
    col_types = detect_column_types(df)

    columns_profile = []
    numeric_cols, text_cols, date_cols = [], [], []

    for col in df.columns:
        series = df[col]
        col_type = col_types[col]
        non_null = int(series.notna().sum())
        missing = int(series.isna().sum())
        missing_pct = round((missing / n_rows) * 100, 2) if n_rows else 0.0
        unique = int(series.nunique(dropna=True))
        examples = [
            _clean_scalar(v) for v in series.dropna().unique()[:5]
        ]

        entry = {
            "name": col,
            "type": col_type,
            "non_null_count": non_null,
            "missing_count": missing,
            "missing_pct": missing_pct,
            "unique_values": unique,
            "example_values": examples,
        }

        if col_type == "numeric":
            numeric_cols.append(col)
            desc = series.astype(float).describe()
            entry.update({
                "mean": _clean_scalar(desc.get("mean")),
                "median": _clean_scalar(series.astype(float).median()),
                "min": _clean_scalar(desc.get("min")),
                "max": _clean_scalar(desc.get("max")),
                "std": _clean_scalar(desc.get("std")),
                "p25": _clean_scalar(series.astype(float).quantile(0.25)),
                "p75": _clean_scalar(series.astype(float).quantile(0.75)),
            })
        elif col_type == "date":
            text_cols_dates = pd.to_datetime(series, errors="coerce", format="mixed") \
                if not pd.api.types.is_datetime64_any_dtype(series) else series
            date_cols.append(col)
            earliest = text_cols_dates.min()
            latest = text_cols_dates.max()
            entry.update({
                "earliest_date": _clean_scalar(earliest),
                "latest_date": _clean_scalar(latest),
                "range_days": int((latest - earliest).days) if pd.notna(earliest) and pd.notna(latest) else None,
            })
        else:
            text_cols.append(col)
            value_counts = series.dropna().astype(str).value_counts().head(5)
            entry["most_common_values"] = [
                {"value": k, "count": int(v)} for k, v in value_counts.items()
            ]
            lengths = series.dropna().astype(str).str.len()
            entry["avg_length"] = _clean_scalar(round(lengths.mean(), 2)) if len(lengths) else None

        columns_profile.append(entry)

    duplicate_rows = int(df.duplicated().sum())
    total_missing = int(df.isna().sum().sum())

    return {
        "row_count": n_rows,
        "column_count": n_cols,
        "columns": columns_profile,
        "numeric_columns": numeric_cols,
        "text_columns": text_cols,
        "date_columns": date_cols,
        "duplicate_rows": duplicate_rows,
        "duplicate_pct": round((duplicate_rows / n_rows) * 100, 2) if n_rows else 0.0,
        "total_missing_values": total_missing,
        "total_missing_pct": round((total_missing / (n_rows * n_cols)) * 100, 2) if n_rows and n_cols else 0.0,
    }


def sample_rows(df: pd.DataFrame, n: int = 10) -> list:
    head = df.head(n)
    records = []
    for _, row in head.iterrows():
        records.append({col: _clean_scalar(row[col]) for col in df.columns})
    return records
