"""
DataForge AI - Report generation.
Assembles verified statistics (and, optionally, AI interpretation of
those statistics) into a professional report, exportable as
Markdown / HTML / TXT / JSON.
"""
from __future__ import annotations
import json
from datetime import datetime, timezone

REPORT_TITLES = {
    "dataset_profile": "Dataset Profile Report",
    "data_quality": "Data Quality Report",
    "business_analysis": "Business Analysis Report",
    "kpi": "KPI Report",
    "trend": "Trend Analysis Report",
    "executive_summary": "Executive Summary",
}


def build_report_markdown(report_type: str, dataset_name: str, stats: dict,
                           ai_section: dict | None, ai_provider: str | None) -> str:
    title = REPORT_TITLES.get(report_type, "DataForge AI Report")
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# {title}",
        "",
        f"**Dataset:** {dataset_name}  ",
        f"**Generated:** {now}  ",
        f"**AI Provider Used:** {ai_provider or 'None (deterministic analysis only)'}  ",
        "",
        "---",
        "",
        "## Verified Statistics",
        "",
        "_All figures below were calculated directly from the dataset using pandas/numpy. "
        "None of these numbers were generated by an AI model._",
        "",
        "```json",
        json.dumps(stats, indent=2, default=str)[:6000],
        "```",
        "",
    ]

    if ai_section:
        lines += ["---", "", "## AI Interpretation", ""]
        if ai_section.get("executive_summary"):
            lines += ["### Executive Summary", "", ai_section["executive_summary"], ""]
        if ai_section.get("key_findings"):
            lines += ["### Key Findings", ""]
            for kf in ai_section["key_findings"]:
                if isinstance(kf, dict):
                    lines.append(f"- **{kf.get('finding', '')}** ({kf.get('importance', 'medium')}) - {kf.get('evidence', '')}")
                else:
                    lines.append(f"- {kf}")
            lines.append("")
        for key, heading in (
            ("trends", "Trends"), ("anomalies", "Anomalies"),
            ("business_implications", "Potential Business Implications"),
            ("questions_worth_investigating", "Questions Worth Investigating"),
            ("recommended_next_analysis", "Recommended Next Analysis"),
            ("top_insights", "Top Insights"), ("opportunities", "Opportunities"),
            ("risks", "Risks"), ("next_steps", "Suggested Next Steps"),
        ):
            if ai_section.get(key):
                lines += [f"### {heading}", ""]
                lines += [f"- {item}" for item in ai_section[key]]
                lines.append("")
        if ai_section.get("limitations") or ai_section.get("data_limitations"):
            lims = ai_section.get("limitations") or ai_section.get("data_limitations")
            lines += ["### Limitations", ""] + [f"- {item}" for item in lims] + [""]

    lines += [
        "---",
        "",
        "_This report distinguishes calculated facts (verified statistics section) from "
        "AI-generated explanations (AI interpretation section). Correlation does not imply causation._",
        "",
        "Built by Oleh Datsyk - DataForge AI",
    ]
    return "\n".join(lines)


def markdown_to_html(md: str, title: str) -> str:
    # Minimal, dependency-free markdown -> HTML for report export (headings, lists, code, bold)
    import html as htmllib
    body_lines = []
    in_code = False
    in_list = False
    for raw in md.split("\n"):
        line = raw.rstrip()
        if line.strip().startswith("```"):
            in_code = not in_code
            body_lines.append("<pre>" if in_code else "</pre>")
            continue
        if in_code:
            body_lines.append(htmllib.escape(line))
            continue
        stripped = line.strip()
        if stripped.startswith("# "):
            body_lines.append(f"<h1>{htmllib.escape(stripped[2:])}</h1>")
        elif stripped.startswith("### "):
            body_lines.append(f"<h3>{htmllib.escape(stripped[4:])}</h3>")
        elif stripped.startswith("## "):
            body_lines.append(f"<h2>{htmllib.escape(stripped[3:])}</h2>")
        elif stripped.startswith("- "):
            if not in_list:
                body_lines.append("<ul>")
                in_list = True
            body_lines.append(f"<li>{htmllib.escape(stripped[2:])}</li>")
            continue
        elif stripped == "---":
            body_lines.append("<hr/>")
        elif stripped == "":
            body_lines.append("<br/>")
        else:
            body_lines.append(f"<p>{htmllib.escape(stripped)}</p>")
        if in_list and not stripped.startswith("- "):
            body_lines.append("</ul>")
            in_list = False
    if in_list:
        body_lines.append("</ul>")

    return f"""<!doctype html>
<html><head><meta charset="utf-8"><title>{htmllib.escape(title)}</title>
<style>
body {{ font-family: -apple-system, Segoe UI, Roboto, sans-serif; max-width: 900px; margin: 40px auto; padding: 0 20px; color: #1a1a2e; line-height: 1.6; }}
h1 {{ color: #4338ca; }} h2 {{ color: #4f46e5; margin-top: 32px; }} h3 {{ color: #6366f1; }}
pre {{ background: #f3f4f6; padding: 12px; border-radius: 8px; overflow-x: auto; font-size: 13px; }}
hr {{ border: none; border-top: 1px solid #e5e7eb; margin: 24px 0; }}
</style></head><body>{''.join(body_lines)}</body></html>"""
